### ISSUE TITLE
Crashed after loading recipe

### ISSUE THREAD

**Issue by ABKQPO** [Game4all/gamebosu#279]
```
2024-11-17 12:57:50 [error]: An unhandled error has occurred.
2024-11-17 12:57:50 [error]: System.MissingFieldException: Field not found: 'osu.Game.OsuGame.LocalUserPlaying'.
2024-11-17 12:57:50 [error]: at osu.Game.Rulesets.Gamebosu.Graphics.GamebosuToolbarIcon.<>c__DisplayClass2_0.<load>b__0()
2024-11-17 12:57:50 [error]: at osu.Framework.Graphics.Containers.ClickableContainer.OnClick(ClickEvent e)
2024-11-17 12:57:50 [error]: at osu.Game.Overlays.Toolbar.ToolbarButton.OnClick(ClickEvent e)
2024-11-17 12:57:50 [error]: at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
2024-11-17 12:57:50 [error]: at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
2024-11-17 12:57:50 [error]: at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
2024-11-17 12:57:50 [error]: at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
2024-11-17 12:57:50 [error]: at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
2024-11-17 12:57:50 [error]: at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
2024-11-17 12:57:50 [error]: at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
2024-11-17 12:57:50 [error]: at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2024-11-17 12:57:50 [error]: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2024-11-17 12:57:50 [error]: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
2024-11-17 12:57:50 [error]: at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
2024-11-17 12:57:50 [error]: at osu.Framework.Input.InputManager.Update()
2024-11-17 12:57:50 [error]: at osu.Framework.Input.PassThroughInputManager.Update()
2024-11-17 12:57:50 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-11-17 12:57:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:57:50 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-11-17 12:57:50 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-11-17 12:59:37 [error]: An unhandled error has occurred.
2024-11-17 12:59:37 [error]: System.InvalidOperationException: A KeyBindingInputManager which supports recording is not available
2024-11-17 12:59:37 [error]: at osu.Game.Rulesets.UI.DrawableRuleset`1.SetRecordTarget(Score score)
2024-11-17 12:59:37 [error]: at osu.Game.Screens.Play.Player.PrepareReplay()
2024-11-17 12:59:37 [error]: at osu.Game.Screens.Play.Player.LoadComplete()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Drawable.loadComplete()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:37 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-11-17 12:59:37 [error]: at osu.Framework.Threading.GameThread.processFrame()

2024-11-17 12:59:37 [verbose]: ⚠️ An unhandled error has occurred.
2024-11-17 12:59:37 [verbose]: 
2024-11-17 12:59:37 [verbose]: This error has been automatically reported to the devs.
2024-11-17 12:59:40 [error]: An unhandled error has occurred.
2024-11-17 12:59:40 [error]: System.InvalidOperationException: A KeyBindingInputManager which supports recording is not available
2024-11-17 12:59:40 [error]: at osu.Game.Rulesets.UI.DrawableRuleset`1.SetRecordTarget(Score score)
2024-11-17 12:59:40 [error]: at osu.Game.Screens.Play.Player.prepareAndImportScoreAsync(Boolean forceImport)
2024-11-17 12:59:40 [error]: at osu.Game.Screens.Play.Player.PerformExit(Boolean skipTransition)
2024-11-17 12:59:40 [error]: at osu.Game.Screens.Play.Player.PerformExitWithConfirmation()
2024-11-17 12:59:40 [error]: at osu.Game.Screens.Play.Player.<createOverlayComponents>b__104_0()
2024-11-17 12:59:40 [error]: at osu.Game.Screens.Play.HUD.HoldForMenuButton.<load>b__13_2()
2024-11-17 12:59:40 [error]: at osu.Game.Graphics.Containers.HoldToConfirmContainer.Confirm()
2024-11-17 12:59:40 [error]: at osu.Game.Screens.Play.HUD.HoldForMenuButton.HoldButton.Confirm()
2024-11-17 12:59:40 [error]: at osu.Game.Screens.Play.HUD.HoldForMenuButton.HoldButton.OnPressed(KeyBindingPressEvent`1 e)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.triggerKeyBindingEvent(IDrawable drawable, KeyBindingEvent`1 e)
2024-11-17 12:59:40 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2024-11-17 12:59:40 [error]: at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.PropagatePressed(IEnumerable`1 drawables, InputState state, T pressed, Single scrollAmount, Boolean isPrecise, Boolean repeat)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.handleNewPressed(InputState state, InputKey newKey, Nullable`1 scrollDelta, Boolean isPrecise)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.Handle(UIEvent e)
2024-11-17 12:59:40 [error]: at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.KeyEventManager.HandleButtonDown(InputState state, List`1 targets)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.ButtonEventManager`1.handleButtonDown(InputState state)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.InputManager.HandleKeyboardKeyStateChange(ButtonStateChangeEvent`1 keyboardKeyStateChange)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
2024-11-17 12:59:40 [error]: at osu.Framework.Input.InputManager.Update()
2024-11-17 12:59:40 [error]: at osu.Framework.Input.PassThroughInputManager.Update()
2024-11-17 12:59:40 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-11-17 12:59:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:40 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-11-17 12:59:40 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-11-17 12:59:40 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions.
2024-11-17 12:59:40 [verbose]: ⚠️ An unhandled error has occurred.
2024-11-17 12:59:40 [verbose]: 
2024-11-17 12:59:40 [verbose]: This error has been automatically reported to the devs.
2024-11-17 12:59:42 [error]: An unhandled error has occurred.
2024-11-17 12:59:42 [error]: System.InvalidOperationException: A KeyBindingInputManager which supports recording is not available
2024-11-17 12:59:42 [error]: at osu.Game.Rulesets.UI.DrawableRuleset`1.SetRecordTarget(Score score)
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.Player.prepareAndImportScoreAsync(Boolean forceImport)
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.Player.PerformExit(Boolean skipTransition)
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.Player.PerformExitWithConfirmation()
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.Player.<createOverlayComponents>b__104_0()
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.HUD.HoldForMenuButton.<load>b__13_2()
2024-11-17 12:59:42 [error]: at osu.Game.Graphics.Containers.HoldToConfirmContainer.Confirm()
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.HUD.HoldForMenuButton.HoldButton.Confirm()
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.HUD.HoldForMenuButton.HoldButton.OnPressed(KeyBindingPressEvent`1 e)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.triggerKeyBindingEvent(IDrawable drawable, KeyBindingEvent`1 e)
2024-11-17 12:59:42 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2024-11-17 12:59:42 [error]: at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.PropagatePressed(IEnumerable`1 drawables, InputState state, T pressed, Single scrollAmount, Boolean isPrecise, Boolean repeat)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.handleNewPressed(InputState state, InputKey newKey, Nullable`1 scrollDelta, Boolean isPrecise)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.Handle(UIEvent e)
2024-11-17 12:59:42 [error]: at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.KeyEventManager.HandleButtonDown(InputState state, List`1 targets)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.ButtonEventManager`1.handleButtonDown(InputState state)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.InputManager.HandleKeyboardKeyStateChange(ButtonStateChangeEvent`1 keyboardKeyStateChange)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.InputManager.Update()
2024-11-17 12:59:42 [error]: at osu.Framework.Input.PassThroughInputManager.Update()
2024-11-17 12:59:42 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-11-17 12:59:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:42 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-11-17 12:59:42 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-11-17 12:59:42 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions.
2024-11-17 12:59:42 [verbose]: ⚠️ An unhandled error has occurred.
2024-11-17 12:59:42 [verbose]: 
2024-11-17 12:59:42 [verbose]: This error has been automatically reported to the devs.
2024-11-17 12:59:42 [error]: An unhandled error has occurred.
2024-11-17 12:59:42 [error]: System.InvalidOperationException: A KeyBindingInputManager which supports recording is not available
2024-11-17 12:59:42 [error]: at osu.Game.Rulesets.UI.DrawableRuleset`1.SetRecordTarget(Score score)
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.Player.prepareAndImportScoreAsync(Boolean forceImport)
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.Player.PerformExit(Boolean skipTransition)
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.Player.PerformExitWithConfirmation()
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.Player.<createOverlayComponents>b__104_0()
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.HUD.HoldForMenuButton.<load>b__13_2()
2024-11-17 12:59:42 [error]: at osu.Game.Graphics.Containers.HoldToConfirmContainer.Confirm()
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.HUD.HoldForMenuButton.HoldButton.Confirm()
2024-11-17 12:59:42 [error]: at osu.Game.Screens.Play.HUD.HoldForMenuButton.HoldButton.OnPressed(KeyBindingPressEvent`1 e)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.triggerKeyBindingEvent(IDrawable drawable, KeyBindingEvent`1 e)
2024-11-17 12:59:42 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2024-11-17 12:59:42 [error]: at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.PropagatePressed(IEnumerable`1 drawables, InputState state, T pressed, Single scrollAmount, Boolean isPrecise, Boolean repeat)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.handleNewPressed(InputState state, InputKey newKey, Nullable`1 scrollDelta, Boolean isPrecise)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.Bindings.KeyBindingContainer`1.Handle(UIEvent e)
2024-11-17 12:59:42 [error]: at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.KeyEventManager.HandleButtonDown(InputState state, List`1 targets)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.ButtonEventManager`1.handleButtonDown(InputState state)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.InputManager.HandleKeyboardKeyStateChange(ButtonStateChangeEvent`1 keyboardKeyStateChange)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
2024-11-17 12:59:42 [error]: at osu.Framework.Input.InputManager.Update()
2024-11-17 12:59:42 [error]: at osu.Framework.Input.PassThroughInputManager.Update()
2024-11-17 12:59:42 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-11-17 12:59:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 12:59:42 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-11-17 12:59:42 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-11-17 12:59:42 [verbose]: Too many unhandled exceptions, crashing out.
2024-11-17 12:59:42 [verbose]: ⚠️ Subsequent messages have been logged. Click to view log files.
2024-11-17 12:59:43 [verbose]: Playback discrepancy detected (1 of allowed 5): 24,181.8 vs 24,992.6
2024-11-17 12:59:44 [verbose]: Playback discrepancy detected (2 of allowed 5): 25,056.7 vs 25,820.1
2024-11-17 12:59:49 [verbose]: Video too far out of sync (26200), seeking to 30674.16172366953
2024-11-17 12:59:49 [verbose]: Video too far out of sync (26266.666666666664), seeking to 30674.724880943264
2024-11-17 12:59:49 [verbose]: Host execution state changed to Stopping
2024-11-17 12:59:49 [verbose]: Host execution state changed to Stopped
2024-11-17 12:59:49 [verbose]: Ending high performance session
```

**Comment by Game4all** [comment]
Hey, sorry for the bit delayed reply! Could you please indicate what version of lazer you are seing this one ? thank you

**Comment by ABKQPO** [comment]
2024.1115.3-lazer

**Comment by Game4all** [comment]
No activity on that for a while, I'll be closing that then.
